version: "3"

services:
  ss4-research-www:
    build:
      context: .docker/www
      dockerfile: Dockerfile
    container_name: ss4-research-www
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www/html:cached
    networks:
      - ss4-research
  ss4-research-mysql:
    image: mysql:5.7
    container_name: ss4-research-mysql
    ports:
      - "3306:3306"
    volumes:
      - ss4-research-mysqldata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ss4-research-mysql
      - TZ=Pacific/Auckland
    networks:
      - ss4-research
  ss4-research-redis:
    image: redis:alpine
    container_name: ss4-research-redis
    volumes:
      - ss4-research-redisdata:/data
    networks:
      - ss4-research
  ss4-research-mailhog:
    image: mailhog/mailhog:latest
    container_name: ss4-research-mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - ss4-research

networks:
  ss4-research:
    driver: "bridge"

volumes:
  ss4-research-mysqldata:
    driver: "local"
  ss4-research-redisdata:
    driver: "local"

